# Generated by Django 3.2.13 on 2023-04-22 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoru',
            new_name='category',
        ),
    ]
